# Generated by Django 5.2.1 on 2025-05-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_alter_todo_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="data_completed",
            new_name="date_completed",
        ),
        migrations.AddField(
            model_name="todo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
